kind: Cluster
name: uk-brs-1-prod
labels:
  region: uk-brs-1
talos:
  version: v1.9.3
kubernetes:
  version: v1.32.1
features:
  enableWorkloadProxy: true
  useEmbeddedDiscoveryService: true
  backupConfiguration:
    interval: 1h
patches:
  - name: allow-schedule-control-plane
    inline:
      cluster:
        allowSchedulingOnControlPlanes: true
  - name: pod-security-exemptions
    inline:
      cluster:
        apiServer:
          admissionControl:
            - name: PodSecurity
              configuration:
                exemptions:
                  namespaces:
                    - rook-ceph
                    - metrics
                    - node-feature-discovery
                    - falco
  - name: kubelet-serving-cert-approver
    inline:
      cluster:
        extraManifests:
          - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: true
  - name: podman-fix
    inline:
      machine:
        sysctls:
          user.max_user_namespaces: "10000"
---
kind: ControlPlane
machineClass:
  name: cluster-desired-uk-brs-1-prod
  size: unlimited
