apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argo
  namespace: argo
spec:
  type: kv-v2
  mount: secrets
  path: argo
  destination:
    name: vault-argo
    create: true
  refreshAfter: 30s
  vaultAuthRef: argo-server