apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2024.12.3
      plugin:
        env:
          - name: AVP_TYPE
            value: vault
          - name: VAULT_ADDR
            value: http://vault.vault.svc:8200
          - name: AVP_AUTH_TYPE
            value: k8s
          - name: AVP_K8S_ROLE
            value: argocd
          - name: HELM_VALUES
            value: |
              authentik:
                email:
                  host: "mail.smtp2go.com"
                  port: 587
                  use_tls: true
                  username: "<path:secrets/data/authentik#smtp-user>"
                  password: "<path:secrets/data/authentik#smtp-pass>"
                  from: "auth@morrislan.net"
                error_reporting:
                  enabled: true
                events:
                  context_processors:
                    geoip: "/tmp/non-existent-file"
                    asn: "/tmp/non-existent-file"
                secret_key: <path:secrets/data/authentik#secret-key>
                postgresql:
                  password: <path:secrets/data/authentik#db-pass>
              postgresql:
                enabled: true
                volumePermissions:
                  enabled: true
                primary:
                  livenessProbe:
                    enabled: false
                  initdb:
                    user: authentik
                    password: <path:secrets/data/authentik#db-pass>
                image:
                  registry: docker.io
                  repository: bitnami/postgresql
                  tag: 16.4.0
                auth:
                  password: <path:secrets/data/authentik#db-pass>
              redis:
                enabled: true
              server:
                ingress:
                  enabled: true
                  annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                  hosts:
                    - auth.morrislan.net

                  tls:
                    - secretName: authentik-tls
                      hosts:
                        - auth.morrislan.net
                replicas: 1
                metrics:
                  enabled: true
                  serviceMonitor:
                    enabled: true
              worker:
                replicas: 1
              prometheus:
                rules:
                  enabled: true
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/authentik'
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
