name: "Build"

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  homepage:
    name: "homepage"
    runs-on: ubuntu-latest
    container:
      image: git.morrislan.net/morrislan/podman-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: podman build /workspace/MorrisLAN/morrislan/apps/homepage -t git.morrislan.net/morrislan/homepage:${{ github.sha }}

      - name: Import Secrets
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.morrislan.net
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/gitea ci-docker-token | DOCKER_TOKEN ;

      - name: Login to Registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: echo ${{ env.DOCKER_TOKEN }} | podman login git.morrislan.net --username morrislan-gitea --password-stdin

      - name: Push dev
        if: github.ref == 'refs/heads/dev'
        run:  |
          podman tag git.morrislan.net/morrislan/homepage:${{ github.sha }} git.morrislan.net/morrislan/homepage:dev
          podman push git.morrislan.net/morrislan/homepage:dev

      - name: Push latest
        if: github.ref == 'refs/heads/main'
        run: |
          podman tag git.morrislan.net/morrislan/homepage:${{ github.sha }} git.morrislan.net/morrislan/homepage:latest
          podman push git.morrislan.net/morrislan/homepage:latest
