apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: netbird
  namespace: netbird
  labels:
    app: netbird-router-prod
spec:
  type: kv-v2
  mount: secrets
  path: netbird
  destination:
    name: vault-netbird
    create: true
  refreshAfter: 30s
  vaultAuthRef: netbird-router-prod