apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.4.1
      helm:
        valuesObject:
          grafana:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
              hosts:
                - metrics.morrislan.net
              tls:
                - secretName: metrics-tls
                  hosts:
                    - metrics.morrislan.net
            grafana.ini:
              server:
                root_url: https://metrics.morrislan.net/
            persistence:
              enabled: true
              type: pvc
              accessModes:
                - ReadWriteOnce
              size: 5Gi
          prometheus:
            annotations:
              argocd.argoproj.io/skip-health-check: 'true'
            prometheusSpec:
              podMonitorSelectorNilUsesHelmValues: false
              serviceMonitorSelectorNilUsesHelmValues: false
              serviceMonitorSelector: {}
              serviceMonitorNamespaceSelector: {}
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/metrics'
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
