apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-mgmt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://betterstackhq.github.io/logs-helm-chart
      chart: betterstack-logs
      targetRevision: v1.1.6
      plugin:
        env:
          - name: AVP_TYPE
            value: vault
          - name: VAULT_ADDR
            value: http://vault.vault.svc:8200
          - name: AVP_AUTH_TYPE
            value: k8s
          - name: AVP_K8S_ROLE
            value: argocd-core
          - name: HELM_VALUES
            value: |
              vector:
                customConfig:
                  sinks:
                    better_stack_http_sink:
                      auth:
                        strategy: "bearer"
                        token: "<path:secrets/data/betterstack#mgmt-source-token>"
                    better_stack_http_metrics_sink:
                      auth:
                        strategy: "bearer"
                        token: "<path:secrets/data/betterstack#mgmt-source-token>"

    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/metrics/mgmt'
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
