apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm-chart.oneuptime.com/
      chart: oneuptime
      targetRevision: 7.0.3652
      helm:
        valuesObject:
          host: "uptime.morrislan.net"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: "workloadKind"
                        operator: "In"
                        values:
                          - "metrics"
          tolerations:
            - key: "workloadKind"
              operator: "Equal"
              value: "metrics"
              effect: "NoSchedule"
          oneuptimeIngress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            className: nginx
            hosts:
              - "uptime.morrislan.net"
            tls:
              enabled: true
              hosts:
                - host: "uptime.morrislan.net"
                  secretName: oneuptime-tls

    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/oneuptime'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: oneuptime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
