apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  type: kv-v2
  mount: secrets
  path: cloudflare
  destination:
    name: cloudflare
    create: true
  refreshAfter: 30s
  vaultAuthRef: external-dns