apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hoopdev
  namespace: hoopdev
spec:
  type: kv-v2
  mount: secrets
  path: hoopdev
  destination:
    name: vault-hoopdev
    create: true
  refreshAfter: 30s
  vaultAuthRef: hoopdev