apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster-uk-brs-1-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: v1.16.3
      helm:
        valuesObject:
          clusterName: rook-ceph-cluster-uk-brs-1-prod
          monitoring:
            enabled: true
            createPrometheusRules: true
          cephClusterSpec:
            mgr:
              modules:
                - name: rook
                  enabled: true
            storage:
              useAllNodes: true
              useAllDevices: true

    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/rook-ceph/uk-brs-1-prod'

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
