apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/generic-device-plugin'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
