apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  sources:
     - repoURL: https://oauth2-proxy.github.io/manifests
       chart: oauth2-proxy
       targetRevision: 7.10.2
       plugin:
         env:
           - name: AVP_TYPE
             value: vault
           - name: VAULT_ADDR
             value: http://vault.vault.svc:8200
           - name: AVP_AUTH_TYPE
             value: k8s
           - name: AVP_K8S_ROLE
             value: argocd
           - name: HELM_VALUES
             value: |
               ingress:
                 enabled: true
                 path: /
                 pathType: ImplementationSpecific
                 annotations:
                   cert-manager.io/cluster-issuer: letsencrypt
                 hosts:
                   - uptime-kuma.morrislan.net
                 tls:
                   - secretName: uptime-kuma-admin-tls
                     hosts:
                       - uptime-kuma.morrislan.net
               config:
                 clientID: "<path:secrets/data/uptime-kuma#oidc-client-id>"
                 clientSecret: "<path:secrets/data/uptime-kuma#oidc-client-secret>"
                 cookieSecret: "<path:secrets/data/uptime-kuma#oidc-cookie-secret>"
               extraArgs:
                 provider: oidc
                 provider-display-name: "authentik"
                 oidc-issuer-url: "https://auth.morrislan.net/application/o/uptime-kuma/"
                 skip-provider-button: "true"
                 pass-authorization-header: "true" 
                 upstream: "http://uptime-kuma.uptime-kuma.svc"
                 session-store-type: cookie
                 cookie-refresh: 15m

     - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
       targetRevision: main
       path: 'apps/uptime-kuma'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true