apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.slack: argocd
spec:
  project: default
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 4.20.1
      plugin:
        env:
          - name: AVP_TYPE
            value: vault
          - name: VAULT_ADDR
            value: http://vault.vault.svc:8200
          - name: AVP_AUTH_TYPE
            value: k8s
          - name: AVP_K8S_ROLE
            value: falco
          - name: HELM_VALUES
            value: |
              falco:
                rules_files:
                  - /etc/falco/falco_rules.yaml
                  - /etc/falco/falco-incubating_rules.yaml
                  - /etc/falco/k8s_audit_rules.yaml
                  - /etc/falco/rules.d
                plugins:
                  - name: k8saudit
                    library_path: libk8saudit.so
                    init_config: ""
                    open_params: "http://:9765/k8s-audit"
                  - name: json
                    library_path: libjson.so
                    init_config: ""
                load_plugins: [k8saudit, json]

              falcoctl:
                config:
                  artifact:
                    install:
                      refs: [falco-rules:latest, falco-incubating-rules:latest, k8saudit-rules:latest]
                    follow:
                      refs: [falco-rules:latest, falco-incubating-rules:latest, k8saudit-rules:latest]
              falcosidekick:
                enabled: true
                webui:
                  enabled: true

              services:
                - name: k8saudit-webhook
                  type: ClusterIP
                  ports:
                    - port: 9765
                      targetPort: 9765
                      protocol: TCP
                      name: http

              tty: true
              driver:
                kind: ebpf

              metrics:
                enabled: true
              serviceMonitor:
                create: true
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/falco'
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
