apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://aquasecurity.github.io/helm-charts/
      chart: trivy-operator
      targetRevision: 0.25.0
      helm:
        valuesObject:
          trivy:
            ignoreUnfixed: true
          service:
            headless: false
          serviceMonitor:
            enabled: true
    - repoURL: 'https://git.morrislan.net/morrislan'
      targetRevision: prod
      path: 'apps/trivy-operator'
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: aquasecurity.github.io
      kind: ClusterComplianceReport
      jsonPointers: []