apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: omni
  namespace: omni
spec:
  type: kv-v2
  mount: secrets
  path: omni
  destination:
    name: vault-omni
    create: true
  refreshAfter: 30s
  vaultAuthRef: omni
