apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: omni
  namespace: omni
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: omni
    serviceAccount: omni
