apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflare-access
  namespace: cloudflare-access
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cloudflare-access
    serviceAccount: cloudflare-access
