apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-access
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/cloudflare-access'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudflare-access
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
