apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-access-tunnels
  namespace: cloudflare-access
spec:
  type: kv-v2
  mount: secrets
  path: cloudflare-access/tunnels
  destination:
    name: tunnels
    create: true
  refreshAfter: 30s
  vaultAuthRef: cloudflare-access
