apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: librespeed
  labels:
    app: librespeed
spec:
  selector:
    app: librespeed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
