apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librespeed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://git.morrislan.net/morrislan'
    targetRevision: prod
    path: 'apps/librespeed'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: librespeed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true