apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netbird-router-uk-brs-1-prod
  namespace: netbird
spec:
  selector:
    matchLabels:
      app: netbird-router-uk-brs-1-prod
  template:
    metadata:
      labels:
        app: netbird-router-uk-brs-1-prod
    spec:
      containers:
        - name: netbird
          image: netbirdio/netbird:0.37.0
          env:
            - name: NB_MANAGEMENT_URL
              value: "https://vpn.morrislan.net:33073"
            - name: NB_ADMIN_URL
              value: "https://vpn.morrislan.net:443"
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-netbird
                  key: router-uk-brs-1-prod-key
            - name: NB_HOSTNAME
              value: "router-uk-brs-1-prod"
            - name: NB_LOG_LEVEL
              value: "info"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RESOURCE
                - SYS_ADMIN
