apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: netbird-router-uk-brs-1-prod
  namespace: netbird
  labels:
    app: netbird-router-uk-brs-1-prod
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: netbird-router-uk-brs-1-prod
    serviceAccount: netbird-router-uk-brs-1-prod
