apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.29.1
      helm:
        valuesObject:
          ui:
            enabled: true
          server:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
              hosts:
                - host: vault.morrislan.net
              tls:
                - secretName: vault-tls
                  hosts:
                    - vault.morrislan.net
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: 0.9.1
      helm:
        valuesObject:
          defaultVaultConnection:
            enabled: true
            address: "http://vault.vault.svc:8200"
            skipTLSVerify: false
            # - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
            #   targetRevision: main
            #   path: 'apps/vault'
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
