name: "Nix Build"
on:
  push:
  pull_request:
  workflow_dispatch:
      
jobs:
  srv-cfzt-01:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Inject secrets
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
      run: |
        sed -i "s/SECRET_CFZT_HOME_TUNNEL_TOKEN/${{ secrets.CFZT_HOME_TUNNEL_TOKEN }}/" ./nix/modules/cfzt/tunnel-home.nix
        sed -i "s/SECRET_CFZT_BEACON_HOME_KEY/${{ secrets.CFZT_BEACON_HOME_KEY }}/" ./nix/modules/cfzt/beacon-home.nix
        sed -i "s/SECRET_CFZT_BEACON_HOME_CERT/${{ secrets.CFZT_BEACON_HOME_CERT }}/" ./nix/modules/cfzt/beacon-home.nix
    - name: Build image
      env:
        NIX_PATH: "nixpkgs=channel:nixos-23.11"
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.sdImage \
          -I nixos-config=./nix/${{ github.job }}.nix \
          --option sandbox false
    - name: Export image
      run : |
        /run/current-system/sw/bin/mkdir -p /build/output/nix
        /run/current-system/sw/bin/cp -f ./result/sd-image/*.img.zst /build/output/nix/${{ github.job }}.img.zst
    - name: Get image hash
      run : /run/current-system/sw/bin/sha256 /build/output/nix/${{ github.job }}.img.zst

  vm-maxdev01:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Inject secrets
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
      run: |
        sed -i "s/SECRET_GH_RUNNER_TOKEN/${{ secrets.GH_RUNNER_TOKEN }}/" ./nix/modules/cicd/github-runners/home-aarch64.nix
    - name: Build image
      env:
        NIX_PATH: "nixpkgs=channel:nixos-23.11"
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.image \
          -I nixos-config=./nix/${{ github.job }}.nix \
          --option sandbox false
    - name: Export image
      run : |
        /run/current-system/sw/bin/mkdir -p /build/output/nix
        /run/current-system/sw/bin/cp -f ./result/nixos.qcow2 /build/output/nix/${{ github.job }}.qcow2
    - name: Get image hash
      run : /run/current-system/sw/bin/sha256 /build/output/nix/${{ github.job }}.qcow2
