apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: gitea
  namespace: gitea
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: gitea
    serviceAccount: gitea
