apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 10.6.0
      helm:
        valuesObject:
          signing:
            enabled: true
            gpgHome: /data/git/.gnupg
            existingSecret: vault-gitea
          actions:
            statefulset:
              actRunner:
                config: |
                  log:
                    level: debug
                  cache:
                    enabled: false
                  runner:
                    labels:
                      - "ubuntu-latest:docker://docker.io/library/node:22-bullseye"
            enabled: true
            existingSecret: vault-gitea
            existingSecretKey: runner-mgmt-token
          gitea:
            config:
              repository.signing:
                SIGNING_KEY: 9618C0C6E9D833D1
                SIGNING_NAME: MorrisLAN Gitea
                SIGNING_EMAIL: git@morrislan.net
                INITIAL_COMMIT: always
                WIKI: always
                CRUD_ACTIONS: always
                MERGES: always
              server:
                OFFLINE_MODE: false
                DISABLE_SSH: true
              service:
                DISABLE_REGISTRATION: true
                REQUIRE_SIGNIN_VIEW: false
                SHOW_REGISTRATION_BUTTON: false
              openid:
                ENABLE_OPENID_SIGNIN: false
                ENABLE_OPENID_SIGNUP: true
              oauth2_client:
                ENABLE_AUTO_REGISTRATION: true
            admin:
              existingSecret: vault-gitea
              email: git@morrislan.net
          redis-cluster:
            enabled: false
          postgresql-ha:
            enabled: false
          redis:
            enabled: true
          postgresql:
            enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/proxy-body-size: 600m
            hosts:
              - host: git.morrislan.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: gitea-tls
                hosts:
                  - git.morrislan.net
    - repoURL: 'https://git.morrislan.net/MorrisLAN/morrislan'
      targetRevision: main
      path: 'apps/gitea'
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  ignoreDifferences:
    - kind: "*"
      group: "*"
      jsonPointers:
        - /spec/volumeClaimTemplates
