apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea
  namespace: gitea
spec:
  type: kv-v2
  mount: secrets
  path: gitea
  destination:
    name: vault-gitea
    create: true
  refreshAfter: 30s
  vaultAuthRef: gitea